defaults: &defaults
  working_directory: /workspace
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: nwb build
          command: npm run build
      - run:
          name: copy ci config
          command: cp -r .circleci/ ./styleguide/.circleci/
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - package-lock.json
      - persist_to_workspace:
          root: /workspace
          paths:
            - es
            - lib
            - styleguide
            - package.json
            - .git
  deploy:
      <<: *defaults
      steps:
        - attach_workspace:
            at: /workspace
        - run:
            name: git config
            command: git config --global user.email "deploy@circleci.com" && git config --global user.name "Circle CI"
        - run:
            name: ssh alias override key verification
            command: alias ssh='ssh -o StrictHostKeyChecking=no'  && mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
        - run:
            name: install gh-pages
            command: npm i gh-pages
        - run:
            name: gh-pages deploy
            command: npm run deploy
        - persist_to_workspace:
          root: ~/repo
          paths:
            - es
            - lib
            - package.json
  publish:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
        - run:
            name: Publish package
            command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
      - publish:
          requires:
            - deploy
          filters:
            branches:
              only: source